- name: My daily schedule at midnight
  cron: "1 0 * * *"
  data:
    asset_external_name: "Site:3W:PDG-M33-158"
    asset_time_series_external_name: "Site:3W:PDG-M33-158_pressure"
    asset_time_series_id: 1495620710607510
    event_one_file_name: "DRAWN_00009.csv"
    file_id: 1996920632623235
