- name: 3W daily Events schedule at midnight
  cron: "1 0 * * *"
  data:

    data_set_id: 1538933333954333
    assets:
    - asset_name : "Site:3W:TPT-64-7434"
      event_data:
      - id: 1
        event_type: 1
        file_id: 1996920632623235
        file_name: DRAWN_00009.csv
      - id: 2
        event_type: 3
        file_id: 3823110183409911
        file_name: SIMULATED_00074.csv
      - id: 3
        event_type: 4
        file_id: 1771442960445705
        file_name: WELL-00001_20170320190146.csv
      - id: 4
        event_type: 5
        file_id: 2700397123964791
        file_name: SIMULATED_00439.csv
      - id: 5
        event_type: 6
        file_id: 3313360022330985
        file_name: WELL-00002_20140212170333.csv
      - id: 6
        event_type: 7
        file_id: 7083372046210856
        file_name: DRAWN_00010.csv
      - id: 7
        event_type: 8
        file_id: 1204513390785907
        file_name: SIMULATED_00001.csv
    - asset_name : "Site:3W:PDG-M33-158"
      event_data:
      - id: 1
        event_type: 8
        file_id: 1204513390785907
        file_name: SIMULATED_00001.csv
      - id: 2
        event_type: 7
        file_id: 7083372046210856
        file_name: DRAWN_00010.csv
      - id: 3
        event_type: 6
        file_id: 3313360022330985
        file_name: WELL-00002_20140212170333.csv
      - id: 4
        event_type: 0
        file_id: 2700397123964791
        file_name: SIMULATED_00439.csv
      - id: 5
        event_type: 4
        file_id: 1771442960445705
        file_name: WELL-00001_20170320190146.csv
      - id: 6
        event_type: 3
        file_id: 3823110183409911
        file_name: SIMULATED_00074.csv
      - id: 7
        event_type: 1
        file_id: 1996920632623235
        file_name: DRAWN_00009.csv
